---
# role: jomrr.dhcpd
# file: molecule/default/molecule.yml

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alpine-dhcpd
    image: "jomrr/molecule-alpine:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: arch-dhcpd
    image: "jomrr/molecule-archlinux:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: centos-dhcpd
    image: "jomrr/molecule-centos:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: debian-dhcpd
    image: "jomrr/molecule-debian:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: fedora-dhcpd
    image: "jomrr/molecule-fedora:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: opensuse-dhcpd
    image: "jomrr/molecule-opensuse:15"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: tumbleweed-dhcpd
    image: "jomrr/molecule-opensuse:tumbleweed"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: oracle-dhcpd
    image: "jomrr/molecule-oraclelinux:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
  - name: ubuntu-dhcpd
    image: "jomrr/molecule-ubuntu:latest"
    command: ""
    pre_build_image: true
    privileged: true
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        dhcpd_role_enabled: true
verifier:
  name: ansible
